### ISSUE TITLE
Detect string interpolation variations

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-conditional#22]
if we have a project like this

![screen shot 2016-11-23 at 11 59 05](https://cloud.githubusercontent.com/assets/724877/20566573/4e0cc342-b174-11e6-9844-91c3b57c4d8b.png)

and `index.js` conditionally loads a locale module using the following syntax

```javascript
import i18n from 'locale/#{lang}';
```

We want to be able to detect all possible variations by globing the file system, in the current example the variations are:

```javascript
[ 'locale/ar', 'locale/en', 'locale/es', 'locale/hi', 'locale/zh' ]
```

We need to make sure this logic takes into account `map` and `paths` configuration.

---
https://github.com/systemjs/builder/blob/ccae8f0385ae40c23a85d4dec39fb082e98d2a69/lib/trace.js#L342

**Comment by matthewp** [comment]
> We need to make sure this logic takes into account map and paths configuration.

While that's a noble goal, I don't personally think that should be a strict-requirement. If it presents too much of a challenge to support full normalization maybe it's ok to assume people aren't going to do weird things in combination with conditionals. Just my opinion here.

**Comment by m-mujica** [comment]
I got it working but realised is too naive

- What if the package name is used in the import, e.g: `import i18n from 'my-app/locale/#{lang}';`
- what if we get a relative import, e.g: `import i18n from '../locale/#{lang};'`

I'm currently grabbing the module name and replacing the conditional syntax part with a glob pattern, in our example:

```javascript
// name === 'locale/#{lang}'

var pattern = name.replace(conditionalRegEx, "**/*.js";
// pattern === 'locale/**/*.js'
```

It is clear now why the other import variations won't work with this approach... Maybe I need to normalise the package name without the conditional syntax and used the normalised name instead.

**Comment by justinbmeyer** [comment]
I'm not sure what ya'll are talking about ... But could this be where we use the System.normalize trick we talked about a long time ago. Replace {} with some identifier, run normalize, replace identifier with {}.

**Comment by m-mujica** [comment]
@justinbmeyer now I'm the one who doesn't know what you're talking about 😰 

Replace `{}` where? are you talking about one of the arguments passed to normalize? 

This issue is about figuring out what bundles should we create when using the string interpolation syntax....

if you have `import 'foo/${bar}'`, we need to figure out  all the possible variations for that interpolation.

What I'm doing now, is using `glob` to match all the files in the 'foo' folder (where `foo` is the module name without the conditional)

**Comment by justinbmeyer** [comment]
I'm not by my computer, and the explanation would be hard to type, but it's a way of knowing how path or map might affect a module name. I think Matthew and I talked about this in a donejs contributors meeting a while ago. 

When I get a moment, I'll post a better explanation.

**Comment by matthewp** [comment]
I think he means do this:

given `foo/${bar}`

```js
loader.normalize(name).then(function(name){
  return loader.locate({ name: name, metadata: {});
}).then(function(address){
  var globbedAddress = address
    .replace("file:", "")
    .replace("${bar}", "**/*")

  // This should give you:
  // /home/matthew/dev/my-project/src/foo/**/*

  glob(globbedAddress).then(function( ...
});
```

The problem here is that you need to reverse the process to have moduleNames for each one of these. Blah.

**Comment by justinbmeyer** [comment]
Yep, assuming that nothing special happens with {,}, and $ characters.

**Comment by m-mujica** [comment]
@matthewp how can I get the module name from the module address?

**Comment by matthewp** [comment]
Well you already have the module names pre-globbing from the `loader.normalize()` call, so you need to do some string interpolation there, post-globbing, I think.

**Comment by m-mujica** [comment]
yeah, take a look at https://github.com/stealjs/steal-conditional/pull/24#issuecomment-262961166, 
I'm trying to figure out now why steal is trying to load `glob` when my app is minified. 

If I build the app with minification turned off, "glob" is not listed as a dependency of "steal-conditional"

![screen shot 2016-11-25 at 11 13 50](https://cloud.githubusercontent.com/assets/724877/20627688/64f5f7bc-b300-11e6-9c17-ca0e4457f2b5.png)

but with the code minified it does, any idea why?

![screen shot 2016-11-25 at 11 16 07](https://cloud.githubusercontent.com/assets/724877/20627712/98293f36-b300-11e6-87c8-52e3d1f00237.png)
