### ISSUE TITLE
Automatic configuration

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-conditional#23]
@matthewp I noticed some plugins (like steal-css, steal-less) don't need any configuration once they are installed, should steal-conditional do something similar?

**Comment by matthewp** [comment]
That's actually going to be changing for steal-css and steal-less.

**Comment by m-mujica** [comment]
@matthewp gotcha, does that mean that those plugin will need configuration? Using the `ext` object? 

I'm guessing we can close this issue then

**Comment by matthewp** [comment]
Will work like this: https://github.com/stealjs/steal-npm/issues/194
