### ISSUE TITLE
Boolean Conditional is not working

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal-conditional#33]
a import like
`require('~/modules/notice-box#?triwala-vk/modules/notice-box-exists');`
where `triwala-vk/modules/notice-box-exists` is the module that exports a boolean does not work.

a error is thrown `Condition modules cannot contain . or / in the name`
https://github.com/stealjs/steal-conditional/blob/master/conditional.js#L58

@m-mujica do you know why `.` and `/` is forbidden?

**Comment by matthewp** [comment]
I think `/` is the problem here, it shouldn't be forbidden should it?

**Comment by m-mujica** [comment]
@matthewp @pYr0x the restriction on using `/` was inherited from the original implementation. I can't remember why it was done that way..... I'll try to remove that and see how it goes.

**Comment by pYr0x** [comment]
@m-mujica and news about this issue?

**Comment by m-mujica** [comment]
@pYr0x I plan to work on this in my spare time or after I'm done with the dev bundle stuff....

**Comment by m-mujica** [comment]
@pYr0x just released v0.3.3. Please, give it a try when you have a chance and let me know how it goes.
