### ISSUE TITLE
Conditional loading seems to cause duplicate dependencies to be bundled

### ISSUE THREAD

**Issue by imaustink** [stealjs/steal-conditional#54]
Here is console output for building the canjs site, showing the same version of flexibility being opened five times.

![canjs_____-bash_____138__48](https://user-images.githubusercontent.com/6282922/31140693-078b050c-a82a-11e7-9935-a8b6f3b38616.png)

CC @matthewp

**Comment by matthewp** [comment]
It displays multiple dependencies but they are not actually built more than once. A problem with the display. I see this in donejs-chat now in DoneJS 2.0:

```
OPENING: /Users/matthew/dev/donejs2-test/donejs-chat/package.json!npm
OPENING: donejs-chat@0.0.0#messages/messages
OPENING: donejs-chat@0.0.0#home.component!done-component@2.0.0#component
OPENING: can-debug@1.0.1#can-debug
OPENING: can-debug@1.0.1#can-debug
OPENING: can-debug@1.0.1#can-debug
OPENING: can-debug@1.0.1#can-debug
```
