### ISSUE TITLE
Think about how to configure bundles

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-conditional#6]
Not sure how this will work, @justinbmeyer had a suggestion here: https://github.com/systemjs/systemjs/issues/285#issuecomment-78293245

We have a `sideBundle` config now, I wonder if we could mark each conditional module like `dates-en`, `dates-es` as as sideBundle during the build.

**Comment by m-mujica** [comment]
the steal-conditional extension adds each of the string interpolation variations (exposed through a `cases` property) to the  `loader.bundle` array.
